<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="Home" Id="{fff73924-f1b4-4ca9-b7bd-6e210259384d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Home extends CraneMovement
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Home">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>